FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && \
    apt-get install -y nginx && \
    rm -rf /var/lib/apt/lists/*

COPY pyproject.toml poetry.lock* /app/
RUN pip install --upgrade pip && \
    pip install "sqlmodel[sqlite]" fastapi uvicorn python-jose bcrypt python-multipart pycryptodome

COPY ./app /app
COPY nginx.conf /etc/nginx/nginx.conf
COPY certs/ /etc/nginx/certs/

COPY start_prod.sh /start.sh
RUN chmod +x /start.sh

EXPOSE 80 443

CMD ["/start.sh"]