FROM python:3.12-slim

WORKDIR /app

COPY pyproject.toml poetry.lock* /app/
RUN pip install --upgrade pip && \
    pip install "sqlmodel[sqlite]" fastapi uvicorn python-jose bcrypt python-multipart pycryptodome

COPY ./app /app

EXPOSE 8000

# Run app with hot reload
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
