# FROM python:3.12-slim

# WORKDIR /app

# RUN pip install --upgrade pip && \
#     pip install "sqlmodel[sqlite]" fastapi uvicorn python-jose bcrypt python-multipart pycryptodome pytest

# COPY ./app /app/tests
# COPY ./tests/unit /app/tests

# # Run tests
# CMD ["pytest"]

FROM python:3.12-slim

WORKDIR /app

# COPY pyproject.toml poetry.lock* /app/
RUN pip install --upgrade pip && \
    pip install "sqlmodel[sqlite]" fastapi uvicorn python-jose bcrypt python-multipart pycryptodome pytest

RUN pip list

COPY pytest.ini /app/
COPY ./app /app/app/
# RUN pip install .

COPY ./tests /app/tests/

ENV PYTHONPATH=/app/app
ENV SECRET_KEY=gouda_kaas

# Run tests
CMD ["pytest"]
